version: "3.1"

services:
  bazarr:
    image: linuxserver/bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /home/dreaser/.config/Bazarr:/config
      - /mnt/nas/Films:/movies
      - /mnt/nas/Series:/tv

    ports:
      - 6767:6767
    restart: unless-stopped
