version: "3.1"

services:
  ombi:
    image: rogueosb/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - /home/dreaser/.config/Ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped


