version: "3.1"

services:
  organizr:
    image: organizrtools/organizr-v2
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3580:80
    volumes:
      - /home/dreaser/.config/Organizrr:/config
    restart: unless-stopped

