version: "2"

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /home/dreaser/.config/Radarr:/config
      - /mnt/nas/Films:/movies
      - /mnt/nas/Download:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/dreaser/.config/Hydra2:/config
      - /mnt/nas/Download:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

