version: "3.1"

services:
  organizr:
    image: organizrtools/organizr-v2
    environment:
      - PUID=1001
      - PGID=1002
    networks:
      - traefik_traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.organizr.rule=Host(`organizr.project.lambla.eu`)"
        - "traefik.http.routers.organizr.entrypoints=web"
        - "traefik.http.services.organizr.loadbalancer.server.port=80"
    volumes:
      - /opt/organizr/config:/config

networks:
  traefik_traefik:
    driver: overlay
    external: true
